# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: yarn
      # - run: yarn build
      # - run: yarn test
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            echo "🛫 Building application"
            npm install
            MONGODB_PASS=${{ secrets.MONGODB_PASS }} REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} npm run build
            cd ..
            echo "🔄 Shutdown docker container ..."
            sudo docker-compose -f docker-compose.prod.yml stop
            echo "🚀 Starting docker container ..."
            sudo docker-compose -f docker-compose.prod.yml up -d
            echo "🏁"

      # - name: slack - GitHub Actions Slack integration
      #   uses: act10ns/slack@v1.2.2
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #     channel: github-action-alerts
      #   if: always()
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
